title: Elementary - Jekyll Blog Theme
name: "Elementary Jekyll Theme"
description: "Simple, light weight, responsive jekyll theme for hackers"

markdown: kramdown
highlighter: rouge
javascript_enabled: true

featured_posts_title: Unrelated
featured_posts:
<<<<<<< Updated upstream
  - url: 'https://jt000111.github.io'
    title: 'Featured post #1'
  - url: 'https://jt000111.github.io'
    title: 'Featured post #2'
  - url: 'https://jt000111.github.io'
    title: 'Featured post #3'
=======
  - url: "#"
    title: "Featured post #1"
  - url: "#"
    title: "Featured post #2"
  - url: "#"
    title: "Featured post #3"
>>>>>>> Stashed changes

collections:
  news:
    title: News
    default_open: false
    output: true
  posts:
    title: Study
    default_open: true
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Study
      permalink: /post/:title
  - scope:
      type: news
    values:
      title: News
      permalink: /news/:title

plugins:
  - jekyll-sitemap
